char* dictuListSource = "def map(list, func) {\n"
"    const temp = [];\n"
"\n"
"    for (var i = 0; i < list.len(); i += 1) {\n"
"        temp.push(func(list[i]));\n"
"    }\n"
"\n"
"    return temp;\n"
"}\n"
"\n"
"def filter(list, func=def(x) => x) {\n"
"    const temp = [];\n"
"\n"
"    for (var i = 0; i < list.len(); i += 1) {\n"
"        const result = func(list[i]);\n"
"        if (result) {\n"
"            temp.push(list[i]);\n"
"        }\n"
"    }\n"
"\n"
"    return temp;\n"
"}\n"
;