class testing {
  static hello() {
    //print this;
  }

  test() {
    print "hello";
    print x;
    print y;
    print q;
    print w;
    print e;
    print r;
    print t;
    print u;
    print i;
    print p;
    print a;
    print s;
    print d;
    print f;
    print g;
    print h;
    print j;
  }

  hi(x,y,q,w,e,r,t,u,m) {
    print "test?";
    print x;
    print y;
    print q;
    print w;
    print e;
    print r;
    print t;
    print u;
  }
}

def x(){}

testing().hi(1,2,3,4,5,6,7,8,9);

print testing().hello;
print testing().hi;
//testing().test(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17);

